version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  sensor:
    build: .
    command: python sensor.py
    depends_on:
      - rabbitmq

  alert_system:
    build: .
    command: python alerts.py
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
# docker-compose up --build
# docker-compose up --scale sensor=3
